# VEDA AI & ML Internship — Task 20

## Sort Dataset Using Pandas

**Name:** Divakar R
**Track:** AI & ML
**Task:** 20 — Sort Dataset
**Tools:** Python, Pandas, Jupyter Notebook

### Objective

To understand how to sort a dataset using numerical and categorical columns in ascending and descending order, including sorting by multiple columns.

### Concepts Covered

* Sorting numerical columns
* Sorting categorical columns
* Ascending and descending order
* Sorting by multiple columns
* Understanding `sort_values()`

In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)
print("Libraries imported successfully!")

Pandas version: 3.0.3
Libraries imported successfully!

In [2]:
data = {
    "Employee_ID": [105, 102, 104, 101, 103, 106, 107, 108],
    "Name": [
        "Arun", "Divya", "Karthik", "Priya",
        "Rahul", "Meena", "Vijay", "Anu"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "HR"
    ],
    "Age": [25, 30, 28, 24, 32, 27, 26, 29],
    "Salary": [
        35000, 45000, 40000, 30000,
        50000, 38000, 42000, 46000
    ]
}

df = pd.DataFrame(data)

print("Employee Dataset Created Successfully!")
df

Employee Dataset Created Successfully!

   Employee_ID     Name Department  Age  Salary
0          105     Arun         IT   25   35000
1          102    Divya         HR   30   45000
2          104  Karthik         IT   28   40000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
5          106    Meena    Finance   27   38000
6          107    Vijay         IT   26   42000
7          108      Anu         HR   29   46000

In [3]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Dataset Shape: (8, 5)

Column Names:
['Employee_ID', 'Name', 'Department', 'Age', 'Salary']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  8 non-null      int64
 1   Name         8 non-null      str
 2   Department   8 non-null      str
 3   Age          8 non-null      int64
 4   Salary       8 non-null      int64
dtypes: int64(3), str(2)
memory usage: 517.0 bytes

In [4]:
ascending_salary = df.sort_values(
    by="Salary",
    ascending=True
)

print("Employees Sorted by Salary: Lowest to Highest")
display(ascending_salary)

Employees Sorted by Salary: Lowest to Highest

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
0          105     Arun         IT   25   35000
5          106    Meena    Finance   27   38000
2          104  Karthik         IT   28   40000
6          107    Vijay         IT   26   42000
1          102    Divya         HR   30   45000
7          108      Anu         HR   29   46000
4          103    Rahul         HR   32   50000

In [5]:
descending_salary = df.sort_values(
    by="Salary",
    ascending=False
)

print("Employees Sorted by Salary: Highest to Lowest")
display(descending_salary)

Employees Sorted by Salary: Highest to Lowest

   Employee_ID     Name Department  Age  Salary
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
6          107    Vijay         IT   26   42000
2          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
0          105     Arun         IT   25   35000
3          101    Priya    Finance   24   30000

In [6]:
ascending_name = df.sort_values(
    by="Name",
    ascending=True
)

print("Employees Sorted by Name: A to Z")
display(ascending_name)

Employees Sorted by Name: A to Z

   Employee_ID     Name Department  Age  Salary
7          108      Anu         HR   29   46000
0          105     Arun         IT   25   35000
1          102    Divya         HR   30   45000
2          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
6          107    Vijay         IT   26   42000

In [7]:
descending_name = df.sort_values(
    by="Name",
    ascending=False
)

print("Employees Sorted by Name: Z to A")
display(descending_name)

Employees Sorted by Name: Z to A

   Employee_ID     Name Department  Age  Salary
6          107    Vijay         IT   26   42000
4          103    Rahul         HR   32   50000
3          101    Priya    Finance   24   30000
5          106    Meena    Finance   27   38000
2          104  Karthik         IT   28   40000
1          102    Divya         HR   30   45000
0          105     Arun         IT   25   35000
7          108      Anu         HR   29   46000

In [8]:
sorted_department = df.sort_values(
    by="Department",
    ascending=True
)

print("Employees Sorted by Department: A to Z")
display(sorted_department)

Employees Sorted by Department: A to Z

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
5          106    Meena    Finance   27   38000
1          102    Divya         HR   30   45000
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
0          105     Arun         IT   25   35000
2          104  Karthik         IT   28   40000
6          107    Vijay         IT   26   42000

In [9]:
ascending_age = df.sort_values(
    by="Age",
    ascending=True
)

print("Employees Sorted by Age: Youngest to Oldest")
display(ascending_age)

Employees Sorted by Age: Youngest to Oldest

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
0          105     Arun         IT   25   35000
6          107    Vijay         IT   26   42000
5          106    Meena    Finance   27   38000
2          104  Karthik         IT   28   40000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
4          103    Rahul         HR   32   50000

In [10]:
descending_age = df.sort_values(
    by="Age",
    ascending=False
)

print("Employees Sorted by Age: Oldest to Youngest")
display(descending_age)

Employees Sorted by Age: Oldest to Youngest

   Employee_ID     Name Department  Age  Salary
4          103    Rahul         HR   32   50000
1          102    Divya         HR   30   45000
7          108      Anu         HR   29   46000
2          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
6          107    Vijay         IT   26   42000
0          105     Arun         IT   25   35000
3          101    Priya    Finance   24   30000

In [11]:
multi_column_sort = df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)

print("Sorted by Department (A-Z) and Salary (High to Low)")
display(multi_column_sort)

Sorted by Department (A-Z) and Salary (High to Low)

   Employee_ID     Name Department  Age  Salary
5          106    Meena    Finance   27   38000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
6          107    Vijay         IT   26   42000
2          104  Karthik         IT   28   40000
0          105     Arun         IT   25   35000

In [12]:
age_salary_sort = df.sort_values(
    by=["Age", "Salary"],
    ascending=[True, True]
)

print("Sorted by Age and Salary in Ascending Order")
display(age_salary_sort)

Sorted by Age and Salary in Ascending Order

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
0          105     Arun         IT   25   35000
6          107    Vijay         IT   26   42000
5          106    Meena    Finance   27   38000
2          104  Karthik         IT   28   40000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
4          103    Rahul         HR   32   50000

In [13]:
sorted_employee_id = df.sort_values(
    by="Employee_ID",
    ascending=True
)

print("Employees Sorted by Employee ID")
display(sorted_employee_id)

Employees Sorted by Employee ID

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
1          102    Divya         HR   30   45000
4          103    Rahul         HR   32   50000
2          104  Karthik         IT   28   40000
0          105     Arun         IT   25   35000
5          106    Meena    Finance   27   38000
6          107    Vijay         IT   26   42000
7          108      Anu         HR   29   46000

In [14]:
reset_sorted_df = df.sort_values(
    by="Salary",
    ascending=False
).reset_index(drop=True)

print("Sorted Dataset with Reset Index")
display(reset_sorted_df)

Sorted Dataset with Reset Index

   Employee_ID     Name Department  Age  Salary
0          103    Rahul         HR   32   50000
1          108      Anu         HR   29   46000
2          102    Divya         HR   30   45000
3          107    Vijay         IT   26   42000
4          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
6          105     Arun         IT   25   35000
7          101    Priya    Finance   24   30000

In [15]:
print("Original Dataset:")
display(df)

temporary_sort = df.sort_values(
    by="Salary",
    ascending=False
)

print("Sorted Dataset:")
display(temporary_sort)

print("Original Dataset Remains Unchanged:")
display(df)

Original Dataset:

   Employee_ID     Name Department  Age  Salary
0          105     Arun         IT   25   35000
1          102    Divya         HR   30   45000
2          104  Karthik         IT   28   40000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
5          106    Meena    Finance   27   38000
6          107    Vijay         IT   26   42000
7          108      Anu         HR   29   46000

Sorted Dataset:

   Employee_ID     Name Department  Age  Salary
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
6          107    Vijay         IT   26   42000
2          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
0          105     Arun         IT   25   35000
3          101    Priya    Finance   24   30000

Original Dataset Remains Unchanged:

   Employee_ID     Name Department  Age  Salary
0          105     Arun         IT   25   35000
1          102    Divya         HR   30   45000
2          104  Karthik         IT   28   40000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
5          106    Meena    Finance   27   38000
6          107    Vijay         IT   26   42000
7          108      Anu         HR   29   46000

In [16]:
df_sorted = df.sort_values(
    by="Salary",
    ascending=False
).copy()

print("Dataset Sorted and Stored in a New DataFrame:")
display(df_sorted)

Dataset Sorted and Stored in a New DataFrame:

   Employee_ID     Name Department  Age  Salary
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
6          107    Vijay         IT   26   42000
2          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
0          105     Arun         IT   25   35000
3          101    Priya    Finance   24   30000

In [17]:
print("Ascending Salary Order:")
display(df.sort_values(by="Salary", ascending=True)[["Name", "Salary"]])

print("Descending Salary Order:")
display(df.sort_values(by="Salary", ascending=False)[["Name", "Salary"]])

Ascending Salary Order:

      Name  Salary
3    Priya   30000
0     Arun   35000
5    Meena   38000
2  Karthik   40000
6    Vijay   42000
1    Divya   45000
7      Anu   46000
4    Rahul   50000

Descending Salary Order:

      Name  Salary
4    Rahul   50000
7      Anu   46000
1    Divya   45000
6    Vijay   42000
2  Karthik   40000
5    Meena   38000
0     Arun   35000
3    Priya   30000

In [18]:
top_3_employees = df.sort_values(
    by="Salary",
    ascending=False
).head(3)

print("Top 3 Highest-Paid Employees:")
display(top_3_employees[["Name", "Department", "Salary"]])

Top 3 Highest-Paid Employees:

    Name Department  Salary
4  Rahul         HR   50000
7    Anu         HR   46000
1  Divya         HR   45000

In [19]:
print("========== TASK 20 SUMMARY ==========")

print("\n1. Original Dataset:")
display(df)

print("\n2. Ascending Salary:")
display(df.sort_values(by="Salary", ascending=True))

print("\n3. Descending Salary:")
display(df.sort_values(by="Salary", ascending=False))

print("\n4. Categorical Sorting:")
display(df.sort_values(by="Department", ascending=True))

print("\n5. Multiple Column Sorting:")
display(
    df.sort_values(
        by=["Department", "Salary"],
        ascending=[True, False]
    )
)

print("\nTASK 20 COMPLETED SUCCESSFULLY!")

========== TASK 20 SUMMARY ==========

1. Original Dataset:

   Employee_ID     Name Department  Age  Salary
0          105     Arun         IT   25   35000
1          102    Divya         HR   30   45000
2          104  Karthik         IT   28   40000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
5          106    Meena    Finance   27   38000
6          107    Vijay         IT   26   42000
7          108      Anu         HR   29   46000

2. Ascending Salary:

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
0          105     Arun         IT   25   35000
5          106    Meena    Finance   27   38000
2          104  Karthik         IT   28   40000
6          107    Vijay         IT   26   42000
1          102    Divya         HR   30   45000
7          108      Anu         HR   29   46000
4          103    Rahul         HR   32   50000

3. Descending Salary:

   Employee_ID     Name Department  Age  Salary
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
6          107    Vijay         IT   26   42000
2          104  Karthik         IT   28   40000
5          106    Meena    Finance   27   38000
0          105     Arun         IT   25   35000
3          101    Priya    Finance   24   30000

4. Categorical Sorting:

   Employee_ID     Name Department  Age  Salary
3          101    Priya    Finance   24   30000
5          106    Meena    Finance   27   38000
1          102    Divya         HR   30   45000
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
0          105     Arun         IT   25   35000
2          104  Karthik         IT   28   40000
6          107    Vijay         IT   26   42000

5. Multiple Column Sorting:

   Employee_ID     Name Department  Age  Salary
5          106    Meena    Finance   27   38000
3          101    Priya    Finance   24   30000
4          103    Rahul         HR   32   50000
7          108      Anu         HR   29   46000
1          102    Divya         HR   30   45000
6          107    Vijay         IT   26   42000
2          104  Karthik         IT   28   40000
0          105     Arun         IT   25   35000

TASK 20 COMPLETED SUCCESSFULLY!

### 1. How do you sort a DataFrame?

We use the Pandas `sort_values()` method to sort a DataFrame by one or more columns.

Example:

```python
df.sort_values(by="Salary")
```

### 2. What does `ascending=False` do?

It sorts values in descending order. For numerical values, the largest value appears first.

Example:

```python
df.sort_values(by="Salary", ascending=False)
```

### 3. Can a DataFrame be sorted by multiple columns?

Yes. We can provide multiple column names in a list and specify the sorting direction for each column.

Example:

```python
df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)
```

### 4. Does `sort_values()` modify the original DataFrame?

By default, it returns a sorted DataFrame without modifying the original DataFrame. We can assign the result to a variable or use `inplace=True` to modify the existing DataFrame.

### 5. What is the difference between ascending and descending order?

* **Ascending:** Smallest to largest, or A to Z.
* **Descending:** Largest to smallest, or Z to A.

### Conclusion

In this task, Pandas was used to sort an employee dataset by numerical and categorical columns. Ascending sorting, descending sorting, multiple-column sorting, and index resetting were demonstrated. Sorting helps organize data and makes analysis and comparisons easier.